# Generated by Django 6.0.1 on 2026-01-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_pessoa_user'),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_usuarios', to='loja.produto'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
